In [31]:
import numpy as np
import pandas as pd
import dask
import time
from scipy.sparse import coo_matrix, find

np.random.seed(1)

# Using readlines()
file1 = open('./com-dblp.ungraph.txt', 'r')
Lines = file1.readlines()
connected = []
 
# Strips the newline character
for line in Lines:
    a = line.split()
    results = list(map(int, a))
    connected.append(results)
    
original = np.asarray(connected)
rng = len(np.unique(original))
vertex = np.unique(original)
mapping = dict(map(lambda t: (t[1], t[0]), enumerate(vertex)))
iterator = map(lambda arr: [mapping[arr[0]],mapping[arr[1]]], original)
gr = np.asarray(list(iterator))

grsp = coo_matrix((np.ones(gr.shape[0]), (gr[:, 0], gr[:, 1])),
                      shape=(rng, rng))
grcsr = grsp.tocsr()
adj = grcsr**2
result = find(adj)

In [32]:
result

(array([     0,      4,      6, ..., 160106, 162371, 166188], dtype=int32),
 array([     2,     10,     11, ..., 317079, 317079, 317079], dtype=int32),
 array([1., 1., 1., ..., 1., 1., 1.]))

In [40]:
t = [[vertex[a],vertex[b]] for a, b in zip(result[0], result[1])]

In [41]:
t.sort(key=lambda arr: arr[0])

In [42]:
t

[[0, 2],
 [0, 5915],
 [0, 6786],
 [0, 7741],
 [0, 7852],
 [0, 7979],
 [0, 8085],
 [0, 8086],
 [0, 9335],
 [0, 9457],
 [0, 10077],
 [0, 10653],
 [0, 10971],
 [0, 12238],
 [0, 12457],
 [0, 13038],
 [0, 13090],
 [0, 13419],
 [0, 13811],
 [0, 14330],
 [0, 14662],
 [0, 15004],
 [0, 15432],
 [0, 16242],
 [0, 16259],
 [0, 16408],
 [0, 16803],
 [0, 17411],
 [0, 17509],
 [0, 17623],
 [0, 18035],
 [0, 18656],
 [0, 19192],
 [0, 19501],
 [0, 21424],
 [0, 21502],
 [0, 22970],
 [0, 23595],
 [0, 25333],
 [0, 26376],
 [0, 27021],
 [0, 27466],
 [0, 28860],
 [0, 28995],
 [0, 29998],
 [0, 31096],
 [0, 33043],
 [0, 33126],
 [0, 33762],
 [0, 33971],
 [0, 34976],
 [0, 35156],
 [0, 35342],
 [0, 36045],
 [0, 36797],
 [0, 36918],
 [0, 37301],
 [0, 37678],
 [0, 37774],
 [0, 38912],
 [0, 39669],
 [0, 40548],
 [0, 40903],
 [0, 44446],
 [0, 44701],
 [0, 44724],
 [0, 44725],
 [0, 46588],
 [0, 47234],
 [0, 47489],
 [0, 49063],
 [0, 49144],
 [0, 50034],
 [0, 53044],
 [0, 53240],
 [0, 53377],
 [0, 53611],
 [0, 54246],

In [43]:
f = open("2hop_final.txt", "a")
for row in t:
    f.write(str(row[0]))
    f.write(' ')
    f.write(str(row[1]))
    f.write('\n')
f.close()